export const europeanCountries = [
  { code: "PL", name: "Polska", flag: "🇵🇱" },
  { code: "AT", name: "Austria", flag: "🇦🇹" },
  { code: "DE", name: "Niemcy", flag: "🇩🇪" },
  { code: "FR", name: "Francja", flag: "🇫🇷" },
  { code: "ES", name: "Hiszpania", flag: "🇪🇸" },
  { code: "IT", name: "Włochy", flag: "🇮🇹" },
  { code: "GB", name: "Wielka Brytania", flag: "🇬🇧" },
  { code: "EN", name: "Anglia", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { code: "SC", name: "Szkocja", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { code: "WL", name: "Walia", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
  { code: "NL", name: "Holandia", flag: "🇳🇱" },
  { code: "BE", name: "Belgia", flag: "🇧🇪" },
  { code: "PT", name: "Portugalia", flag: "🇵🇹" },
  { code: "CH", name: "Szwajcaria", flag: "🇨🇭" },
  { code: "SE", name: "Szwecja", flag: "🇸🇪" },
  { code: "NO", name: "Norwegia", flag: "🇳🇴" },
  { code: "DK", name: "Dania", flag: "🇩🇰" },
  { code: "FI", name: "Finlandia", flag: "🇫🇮" },
  { code: "CZ", name: "Czechy", flag: "🇨🇿" },
  { code: "SK", name: "Słowacja", flag: "🇸🇰" },
  { code: "HU", name: "Węgry", flag: "🇭🇺" },
  { code: "RO", name: "Rumunia", flag: "🇷🇴" },
  { code: "BG", name: "Bułgaria", flag: "🇧🇬" },
  { code: "HR", name: "Chorwacja", flag: "🇭🇷" },
  { code: "RS", name: "Serbia", flag: "🇷🇸" },
  { code: "SI", name: "Słowenia", flag: "🇸🇮" },
  { code: "BA", name: "Bośnia i Hercegowina", flag: "🇧🇦" },
  { code: "ME", name: "Czarnogóra", flag: "🇲🇪" },
  { code: "MK", name: "Macedonia Północna", flag: "🇲🇰" },
  { code: "AL", name: "Albania", flag: "🇦🇱" },
  { code: "GR", name: "Grecja", flag: "🇬🇷" },
  { code: "TR", name: "Turcja", flag: "🇹🇷" },
  { code: "UA", name: "Ukraina", flag: "🇺🇦" },
  { code: "RU", name: "Rosja", flag: "🇷🇺" },
  { code: "BY", name: "Białoruś", flag: "🇧🇾" },
  { code: "LT", name: "Litwa", flag: "🇱🇹" },
  { code: "LV", name: "Łotwa", flag: "🇱🇻" },
  { code: "EE", name: "Estonia", flag: "🇪🇪" },
  { code: "IE", name: "Irlandia", flag: "🇮🇪" },
  { code: "IS", name: "Islandia", flag: "🇮🇸" },
  { code: "LU", name: "Luksemburg", flag: "🇱🇺" },
  { code: "MT", name: "Malta", flag: "🇲🇹" },
  { code: "CY", name: "Cypr", flag: "🇨🇾" },
  { code: "MD", name: "Mołdawia", flag: "🇲🇩" },
  { code: "GE", name: "Gruzja", flag: "🇬🇪" },
  { code: "AM", name: "Armenia", flag: "🇦🇲" },
  { code: "AZ", name: "Azerbejdżan", flag: "🇦🇿" },
  { code: "KZ", name: "Kazachstan", flag: "🇰🇿" },
  { code: "XK", name: "Kosowo", flag: "🇽🇰" },
  { code: "AD", name: "Andora", flag: "🇦🇩" },
  { code: "MC", name: "Monako", flag: "🇲🇨" },
  { code: "SM", name: "San Marino", flag: "🇸🇲" },
  { code: "LI", name: "Liechtenstein", flag: "🇱🇮" },
  { code: "VA", name: "Watykan", flag: "🇻🇦" },
  { code: "FO", name: "Wyspy Owcze", flag: "🇫🇴" },
  { code: "GI", name: "Gibraltar", flag: "🇬🇮" },
  { code: "BR", name: "Brazylia", flag: "🇧🇷" },
  { code: "AR", name: "Argentyna", flag: "🇦🇷" },
  { code: "US", name: "USA", flag: "🇺🇸" },
  { code: "JP", name: "Japonia", flag: "🇯🇵" },
  { code: "KR", name: "Korea Południowa", flag: "🇰🇷" },
  { code: "AU", name: "Australia", flag: "🇦🇺" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬" },
  { code: "GH", name: "Ghana", flag: "🇬🇭" },
  { code: "SN", name: "Senegal", flag: "🇸🇳" },
  { code: "CM", name: "Kamerun", flag: "🇨🇲" },
  { code: "MA", name: "Maroko", flag: "🇲🇦" },
  { code: "EG", name: "Egipt", flag: "🇪🇬" },
  { code: "DZ", name: "Algieria", flag: "🇩🇿" },
  { code: "TN", name: "Tunezja", flag: "🇹🇳" },
  { code: "MX", name: "Meksyk", flag: "🇲🇽" },
  { code: "CO", name: "Kolumbia", flag: "🇨🇴" },
  { code: "CL", name: "Chile", flag: "🇨🇱" },
  { code: "UY", name: "Urugwaj", flag: "🇺🇾" },
];

export function getCountryFlag(code: string | undefined): string {
  if (!code) return "🏳️";
  const country = europeanCountries.find(c => c.code.toUpperCase() === code.toUpperCase());
  return country?.flag || "🏳️";
}

export function getCountryName(code: string | undefined): string {
  if (!code) return "Nieznany";
  const country = europeanCountries.find(c => c.code.toUpperCase() === code.toUpperCase());
  return country?.name || code;
}
